Adding base tf files Generation of yamls failed with these. Following is the trace
docker run --rm -it         -e ENABLE_BPMETADATA                -v ~/Documents/adc/poc/byotf/BringYourOwnTF/BringYourOwnTF/modules/v2:/workspace              gcr.io/cloud-foundation-cicd/cft/developer-tools:1.22           /bin/bash -c 'source /usr/local/bin/task_helper_functions.sh && generate_docs display'
Generating markdown docs with terraform-docs
Skipping . because README.md does not exist.
Generating blueprint metadata
Error: top-level module does not have a readme: stat /workspace/README.md: no such file or directory